In [27]:
import pandas as pd
import numpy as np

#np.array([1,10,21,35,72])
#np.array([[9,8,7],[6,5,4],[3,2,1]])
#np.array([[9,8,7,6,5,4,3,2,1]])


#np.arange(start=1, stop=10, step=1).reshape(3,3)

array_1 = np.linspace(0,20,6)
print (array_1)


array_2 = np.arange(0,20,6)
print(array_2)




mat = np.matrix([[ 1, 4, 9, 121, 144, 169],
                [ 16, 25, 36, 196, 225, 256],
                [ 49, 64, 81, 289, 324, 361]])

print(np.average(mat))


np.cos([0, 1, 2, 3, 4])


list_1 = [1,2,3]
list_2 = [4,5,6]
new_list = list_1 + list_2
print(new_list)

array_1 = np.array([1,2,3])
array_2 = np.array([4,5,6])
new_array = array_1 + array_2
print('***************')

print(new_array)




array_1 = np.array([1, 2, 3, 5, 8])
array_2 = np.array([0, 3, 4, 2, 1])
new_array = array_1+ array_2
final_array = new_array*array_1
print(final_array[2])

[ 0.  4.  8. 12. 16. 20.]
[ 0  6 12 18]
131.66666666666666
[1, 2, 3, 4, 5, 6]
***************
[5 7 9]
21
